jenkins:
  securityRealm:
    local:
      allowsSignup: false
      users:
       - id: xyz
         password: xyz
unclassified:
  location:
    url: http://127.0.0.1:8080/
jobs:
  — file: /usr/local/seedjob.groovy