jenkins:
  securityRealm:
    local:
      allowsSignup: false
      users:
       - id: xyz
         password: xyz
credentials:
  system:
    domainCredentials:
    - credentials:
      - string:
          description: "SonarQube token"
          id: "84827f3c-43b9-4708-b767-e70f87e76e7a"
          scope: GLOBAL
          secret: ${SONAR_TOKEN}
unclassified:
  location:
    url: http://127.0.0.1:8080/
  sonarGlobalConfiguration:
    buildWrapperEnabled: false
    installations:
    - credentialsId: "84827f3c-43b9-4708-b767-e70f87e76e7a"
      name: "SonarQube"
      serverUrl: "http://10.0.0.14:9000"
      triggers:
        skipScmCause: false
        skipUpstreamCause: false
tool:
  git:
    installations:
    - home: "git"
      name: "Default"
  mavenGlobalConfig:
    globalSettingsProvider: "standard"
    settingsProvider: "standard"
  sonarRunnerInstallation:
    installations:
    - name: "SonarQube"
      properties:
      - installSource:
          installers:
          - sonarRunnerInstaller:
              id: "5.0.1.3006"
jobs:
  - script: >
      pipelineJob('spring-petclinic') {
        definition {
          cpsScm {
            scm {
              git {
                remote {
                  url 'https://github.com/sarthak-m-das/Devops-Automation.git'
                }
                branch('jar-ansible-ssh')
                scriptPath 'Jenkinsfile'
              }
            }
          }
        }
      }