jenkins:
  securityRealm:
    local:
      allowsSignup: false
      users:
       - id: xyz
         password: xyz
jobs:
  - script: >
      pipelineJob('spring-petclinic') {
        definition {
          cpsScm {
            scm {
              git {
                remote {
                  url 'https://github.com/sarthak-m-das/Devops-Automation.git'
                }
                branch('jar-ansible-ssh')
                scriptPath 'Jenkinsfile'
              }
            }
          }
        }
      }