---
- name: Deploy Docker container from image
  hosts: your_target_host
  become: yes

  tasks:
    - name: Pull Docker image from Docker Hub
      docker_image:
        name: sythe7/petclinic:tagname
        source: pull

    - name: Run Docker container
      docker_container:
        name: petclinic
        image: sythe7/petclinic:tagname
        state: started
        ports:
          - "8000:8000"
        working_dir: /app
        command: java -jar /app/app.jar --server.port=8000
