version: '3.8'

services:
  sonarqube:
    image: sonarqube
    container_name: autosonarqube
    ports:
      - "9000:9000"
      - "9092:9092"
    networks:
      - auto-jenkins-network
    volumes:
      - sonarqube-data:/opt/sonarqube/data
      - sonarqube-logs:/opt/sonarqube/logs
      - sonarqube-extensions:/opt/sonarqube/extensions

networks:
  auto-jenkins-network:
    name: auto-jenkins-network

volumes:
  sonarqube-data:
  sonarqube-logs:
  sonarqube-extensions:
