FROM ubuntu:latest

# Install Java 17
RUN apt-get update && \
    apt-get install -y software-properties-common && \
    add-apt-repository ppa:openjdk-r/ppa && \
    apt-get update && \
    apt-get install -y openjdk-17-jdk && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

# Set the JAVA_HOME environment variable
ENV JAVA_HOME /usr/lib/jvm/java-17-openjdk-amd64

# Set the path to include Java 17
ENV PATH $JAVA_HOME/bin:$PATH

CMD ["tail", "-f", "/dev/null"]