version: '3.8'

services:
  petclinic:
    image: ubuntu:latest
    container_name: petclinic
    command: tail -f /dev/null
    networks:
      - auto-jenkins-network
    ports:
      - "8000:8000"
      - "2200:22"

networks:
  auto-jenkins-network:
    name: auto-jenkins-network
